version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${SPRING_DATASOURCE_DB}'
      - 'POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}'
      - 'POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}'
    ports:
      - '5432:5432'